### ISSUE TITLE
Gossy does not remember tutorial was already done (maybe #278 cropping up again)

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#299] opened 2024-08-30 21:06 UTC
Today I did another run. Gossy remembered I've played before. But on my next run, I get offered the tutorial again as if I've not played before:

![image](https://github.com/user-attachments/assets/e285009a-50c6-4123-a80f-f9d4f307ec07)
Gossy seems oblivious of previous games.

Does this happen sometimes when an update is pushed, as in, should I not report this? I could also just make a comment on #278, if you prefer that.

**Comment by frnsys** [comment] 2024-08-30 21:52
Strange, I can't seem to reproduce it on my end, but it's possible that it happened because I change a bit about what data was saved/loaded. Does it keep happening even on subsequent runs, or was it just this once?

**Comment by sgitkene** [comment] 2024-08-30 22:18
I seem to be able to provoke it when I click "restart game" in the menu on the top right. But in the instance described above, it just happened after the last run.

![image](https://github.com/user-attachments/assets/6c82273a-1311-4c14-a906-ecd745106377)
"RESTART GAME" button that probably deletes the current save and thus may give Gossy amnesia.

**Comment by frnsys** [comment] 2024-08-31 06:53
should be fixed now, was accidentally deleting all save data (including settings) and not just the game data

**Closed** 2024-08-31 06:52 UTC
